import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { GlobalModalProvider } from "@/components/common/GlobalModalProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin", "latin-ext"],
  display: 'swap',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: 'swap',
});

import { getSiteLogo } from "@/lib/getSiteLogo";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const logoUrl = await getSiteLogo();

  return (
    <html lang="vi">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
        <div className="flex flex-col min-h-screen text-gray-900">
          <Header logoUrl={logoUrl} />
          <main className="flex-1 pb-16 lg:pb-0">
            <GlobalModalProvider>
              {children}
            </GlobalModalProvider>
          </main>
          <Footer logoUrl={logoUrl} />
        </div>
      </body>
    </html>
  );
}
